version: "3"
services:
  waffle_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "33060:33060"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SOCKET: "/var/lib/mysql/mysql.sock"
      MYSQL_HOST: waffle_db

  waffle_dbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=waffle_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - waffle_db
    ports:
      - 3004:80


  waffle_metabase:
    image: metabase/metabase
    ports:
      - "3003:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: waffle_development
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: waffle_db
    depends_on:
      - waffle_db
  
  waffle_redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  waffle_redis_commander:
    image: tenstartups/redis-commander
    command: --redis-host waffle_redis
    links:
      - waffle_redis
    ports:
      - "3005:8081"


  elasticsearch:
    build: elasticsearch
    volumes:
        - es-data:/usr/share/elasticsearch/data/
    ports:
        - 9200:9200
    expose:
        - 9300

  kibana:
    build: kibana
    ports:
        - 3006:5601
  
  waffle_dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8000:8000"
    environment:
      DEFAULT_REGION: ap-northeast-3

  waffle_dynamodb_admin:
    image: instructure/dynamo-local-admin
    ports:
      - "3007:8001"
    environment:
      DYNAMO_ENDPOINT: http://waffle_dynamodb:8000/

  waffle:
    build: ./waffle/
    container_name: waffle
    env_file:
      - variables.env
    tty: true #標準出力on
    stdin_open: true
    depends_on:
      - waffle_db
      - waffle_redis
      - elasticsearch
      - waffle_dynamodb
    ports:
      - "3001:3000"
    volumes:
      - waffle-server-sync:/home/waffle_server
    command: >
              bash -c '
              bundle exec rails db:create && 
              bundle exec rails db:migrate &&
              bundle exec rails db:seed &&
              bundle exec sidekiq -C config/sidekiq.yml -d &&
              rm -f tmp/pids/server.pid &&
              bundle exec rails server -b 0.0.0.0'

volumes:
  waffle-server-sync:
    external: true
  es-data:
    driver: local
