version: "3"
services:
  life_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "33060:33060"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SOCKET: "/var/lib/mysql/mysql.sock"
      MYSQL_HOST: life_db

  life_dbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=life_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - life_db
    ports:
      - 3004:80


  life_metabase:
    image: metabase/metabase
    ports:
      - "3003:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: waffle_development
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: life_db
    depends_on:
      - life_db
  
  life_redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  life_redis_commander:
    image: tenstartups/redis-commander
    command: --redis-host life_redis
    links:
      - life_redis
    ports:
      - "3005:8081"


  elasticsearch:
    build: elasticsearch
    volumes:
        - es-data:/usr/share/elasticsearch/data/
    ports:
        - 9200:9200
    expose:
        - 9300

  kibana:
    build: kibana
    ports:
        - 3006:5601
  
  life_dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8000:8000"
    environment:
      DEFAULT_REGION: ap-northeast-3

  life_dynamodb_admin:
    image: instructure/dynamo-local-admin
    ports:
      - "3007:8001"
    environment:
      DYNAMO_ENDPOINT: http://life_dynamodb:8000/

  life:
    build: ./life/
    container_name: life
    env_file:
      - variables.env
    tty: true #標準出力on
    stdin_open: true
    depends_on:
      - life_db
      - life_redis
      - elasticsearch
      - life_dynamodb
    ports:
      - "3002:3000"
    volumes:
      - life-server-sync:/home/life_server
    command: >
              bash -c '
              bundle exec rails db:create && 
              bundle exec rails db:migrate &&
              bundle exec rails db:seed &&
              bundle exec sidekiq -C config/sidekiq.yml -d &&
              bundle exec rails server -b 0.0.0.0'
  
  life_frontend:
    build: ./life-frontend/
    container_name: life_frontend
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - life-frontend-sync:/life_frontend
    ports:
      - "3001:3000"
    command: yarn run dev

volumes:
  life-server-sync:
    external: true
  life-frontend-sync:
    external: true
  es-data:
    driver: local
