version: "3"
services:
  life_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "33060:33060"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SOCKET: "/var/lib/mysql/mysql.sock"
      MYSQL_HOST: life_db
  
  life_redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  elasticsearch:
    build: elasticsearch
    volumes:
        - es-data:/usr/share/elasticsearch/data/
    ports:
        - 9200:9200
    expose:
        - 9300
  kibana:
    build: kibana
    ports:
        - 5601:5601
  
  life_mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: --smallfiles

  life:
    build: ./life/
    container_name: life
    env_file:
      - variables.env
    tty: true #標準出力on
    stdin_open: true
    depends_on:
      - life_db
      - life_redis
      - elasticsearch
      - life_mongodb
    ports:
      - "3002:3000"
    volumes:
      - life-server-sync:/home/life_server
    command: >
              bash -c '
              bundle exec rails db:create && 
              bundle exec rails db:migrate &&
              bundle exec rails db:seed &&
              bundle exec sidekiq -C config/sidekiq.yml -d &&
              bundle exec rails server -b 0.0.0.0'
  
  life_frontend:
    build: ./life-frontend/
    container_name: life_frontend
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - life-frontend-sync:/life_frontend
    ports:
      - "3001:3000"
    command: yarn run dev

volumes:
  life-server-sync:
    external: true
  life-frontend-sync:
    external: true
  es-data:
        driver: local
